-- Generated by HyprMod

-- Environment
hl.env("XCURSOR_SIZE", "32")

-- Settings
hl.config({
    cursor = {
        no_hardware_cursors = 1,
    },
    decoration = {
        blur = {
            enabled = true,
        },
        dim_inactive = false,
        rounding = 3,
        shadow = {
            enabled = true,
        },
    },
    ecosystem = {
        enforce_permissions = false,
    },
    general = {
        col = {
            active_border = {
                colors = {"rgba(99c1f1ff)", "rgba(8ff0a4ff)"},
            },
        },
        gaps_in = 4,
    },
    input = {
        follow_mouse = 0,
    },
    scrolling = {
        fullscreen_on_one_column = true,
    },
})
