-- Generated by HyprMod

-- Environment
hl.env("XCURSOR_THEME", "WhiteSur-cursors")
hl.env("XCURSOR_SIZE", "32")

-- Settings
hl.config({
    cursor = {
        no_hardware_cursors = 1,
    },
    decoration = {
        blur = {
            enabled = true,
        },
        dim_inactive = false,
        rounding = 3,
        shadow = {
            enabled = true,
        },
    },
    ecosystem = {
        enforce_permissions = false,
    },
    general = {
        gaps_in = 5,
    },
    input = {
        follow_mouse = 0,
    },
})
