-- Generated by HyprMod

-- Environment
hl.env("XCURSOR_THEME", "catppuccin-mocha-dark-cursors")
hl.env("XCURSOR_SIZE", "36")
hl.env("HYPRCURSOR_THEME", "catppuccin-mocha-dark-cursors")
hl.env("HYPRCURSOR_SIZE", "36")

-- Settings
hl.config({
    decoration = {
        blur = {
            enabled = false,
        },
        dim_inactive = true,
        rounding = 0,
        shadow = {
            enabled = false,
        },
    },
    ecosystem = {
        enforce_permissions = true,
    },
    general = {
        gaps_in = 4,
    },
    input = {
        follow_mouse = 3,
    },
})
